name: Build, Test and Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test-release:

    name: build-test-release-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            PLATFORM: linux-x64
            
          - os: macos-latest
            PLATFORM: osx-x64
            
          - os: windows-latest
            PLATFORM: win-x64

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test

      - name: Publish
        run: dotnet publish 'CLI To Do' -r ${{ matrix.PLATFORM }} -c Release --self-contained /p:PublishSingleFile=true /p:PublishTrimmed=true /p:IncludeNativeLibrariesForSelfExtract=true /p:DebugType=None /p:DebugSymbols=false
        
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.PLATFORM }}
          path: 'CLI To Do/bin/Release/net6.0/${{ matrix.PLATFORM }}/publish'